// src/config/SpawnPointsConfig.js
// Spawn points for testing purposes.

export const SPAWN_POINTS_CONFIG = [
  {
    id: "forest_wolves_easy", // Unique ID for this spawn area
    position: { x: -22, y: 0, z: -35 }, // Center of spawn area (Y determined by terrain)
    radius: 20, // Spawn within this world radius
    activationRadius: 100, // Player must be within this radius to activate the spawner
    maxEnemies: 3, // Max enemies concurrently active *from this spawner*
    respawnDelaySeconds: 90, // Time before trying to respawn after count drops below max
    initialSpawnCount: 2, // How many enemies to spawn when activated initially
    spawnList: [
      // Weighted list of enemies
      { enemyId: "wolf_timber", weight: 8 }, // 80% chance
      { enemyId: "wolf_dire", weight: 2 }, // 20% chance
    ],
  },
  {
    id: "forest_wolves_easy2",
    position: { x: 15, y: 0, z: 22 },
    radius: 15,
    activationRadius: 100,
    maxEnemies: 2,
    respawnDelaySeconds: 180,
    initialSpawnCount: 2,
    spawnList: [{ enemyId: "wolf_timber", weight: 1 }],
  },
  {
    id: "mountain_pass_knights",
    position: { x: 35, y: 0, z: 88 },
    radius: 15,
    activationRadius: 100,
    maxEnemies: 1,
    respawnDelaySeconds: 180,
    initialSpawnCount: 1,
    spawnList: [{ enemyId: "rogueknight", weight: 1 }],
  },
  {
    id: "swamp_witches",
    position: { x: -115, y: 0, z: -32 },
    radius: 18,
    activationRadius: 100,
    maxEnemies: 2,
    respawnDelaySeconds: 150,
    initialSpawnCount: 1,
    spawnList: [{ enemyId: "witch", weight: 1 }],
  },
  {
    id: "swamp_witches",
    position: { x: -115, y: 0, z: -78 },
    radius: 18,
    activationRadius: 100,
    maxEnemies: 5,
    respawnDelaySeconds: 150,
    initialSpawnCount: 3,
    spawnList: [{ enemyId: "witch", weight: 1 }],
  },
  {
    id: "forest_wolves_easy",
    position: { x: -110, y: 0, z: -65 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 3,
    respawnDelaySeconds: 90,
    initialSpawnCount: 4,
    spawnList: [
      { enemyId: "wolf_timber", weight: 8 },
      { enemyId: "wolf_dire", weight: 2 },
    ],
  },
  {
    id: "forest_wolves_hard",
    position: { x: 110, y: 0, z: 65 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 15,
    respawnDelaySeconds: 500,
    initialSpawnCount: 11,
    spawnList: [
      { enemyId: "wolf_timber", weight: 5 },
      { enemyId: "wolf_dire", weight: 5 },
    ],
  },
  {
    id: "forest_wolves_hard",
    position: { x: 110, y: 0, z: -65 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 15,
    respawnDelaySeconds: 500,
    initialSpawnCount: 7,
    spawnList: [
      { enemyId: "wolf_timber", weight: 5 },
      { enemyId: "wolf_dire", weight: 5 },
    ],
  },
  {
    id: "forest_wolves_hard",
    position: { x: -65, y: 0, z: 110 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 15,
    respawnDelaySeconds: 500,
    initialSpawnCount: 7,
    spawnList: [
      { enemyId: "wolf_timber", weight: 5 },
      { enemyId: "wolf_dire", weight: 5 },
    ],
  },
  {
    id: "mountain_pass_knights",
    position: { x: -35, y: 0, z: 95 },
    radius: 15,
    activationRadius: 100,
    maxEnemies: 1,
    respawnDelaySeconds: 180,
    initialSpawnCount: 1,
    spawnList: [{ enemyId: "rogueknight", weight: 1 }],
  },

  {
    id: "forest_wolves_easy_opposite",
    position: { x: 20, y: 0, z: -25 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 3,
    respawnDelaySeconds: 90,
    initialSpawnCount: 2,
    spawnList: [
      { enemyId: "wolf_timber", weight: 8 },
      { enemyId: "wolf_dire", weight: 2 },
    ],
  },
  {
    id: "mountain_pass_knights_opposite",
    position: { x: -166, y: 0, z: 175 },
    radius: 15,
    activationRadius: 100,
    maxEnemies: 3,
    respawnDelaySeconds: 180,
    initialSpawnCount: 2,
    spawnList: [{ enemyId: "rogueknight", weight: 1 }],
  },
  {
    id: "swamp_witches_opposite_1",
    position: { x: 55, y: 0, z: -72 },
    radius: 18,
    activationRadius: 100,
    maxEnemies: 2,
    respawnDelaySeconds: 150,
    initialSpawnCount: 1,
    spawnList: [{ enemyId: "witch", weight: 1 }],
  },
  {
    id: "swamp_witches_opposite_2",
    position: { x: 115, y: 0, z: -78 },
    radius: 18,
    activationRadius: 100,
    maxEnemies: 5,
    respawnDelaySeconds: 150,
    initialSpawnCount: 3,
    spawnList: [{ enemyId: "witch", weight: 1 }],
  },
  {
    id: "swamp_witches_test",
    position: { x: 167, y: 0, z: -174 },
    radius: 18,
    activationRadius: 100,
    maxEnemies: 5,
    respawnDelaySeconds: 150,
    initialSpawnCount: 3,
    spawnList: [{ enemyId: "witch", weight: 1 }],
  },
  {
    id: "swamp_witches_test_2",
    position: { x: -127, y: 0, z: -130 },
    radius: 18,
    activationRadius: 100,
    maxEnemies: 5,
    respawnDelaySeconds: 150,
    initialSpawnCount: 3,
    spawnList: [{ enemyId: "witch", weight: 1 }],
  },
  {
    id: "forest_wolves_easy_opposite_2",
    position: { x: 110, y: 0, z: -65 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 4,
    respawnDelaySeconds: 90,
    initialSpawnCount: 3,
    spawnList: [
      { enemyId: "wolf_timber", weight: 8 },
      { enemyId: "wolf_dire", weight: 2 },
    ],
  },
  {
    id: "forest_wolves_easy_opposite_3",
    position: { x: 86, y: 0, z: -169 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 4,
    respawnDelaySeconds: 90,
    initialSpawnCount: 3,
    spawnList: [
      { enemyId: "wolf_timber", weight: 8 },
      { enemyId: "wolf_dire", weight: 2 },
    ],
  },
  {
    id: "forest_wolves_easy_opposite_4",
    position: { x: 23, y: 0, z: -150 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 4,
    respawnDelaySeconds: 90,
    initialSpawnCount: 3,
    spawnList: [
      { enemyId: "wolf_timber", weight: 8 },
      { enemyId: "wolf_dire", weight: 2 },
    ],
  },
  {
    id: "forest_wolves_easy_opposite_5",
    position: { x: 19, y: 0, z: 151 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 6,
    respawnDelaySeconds: 90,
    initialSpawnCount: 4,
    spawnList: [
      { enemyId: "wolf_timber", weight: 8 },
      { enemyId: "wolf_dire", weight: 2 },
    ],
  },
  {
    id: "forest_wolves_hard_opposite_1",
    position: { x: -110, y: 0, z: 65 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 15,
    respawnDelaySeconds: 500,
    initialSpawnCount: 11,
    spawnList: [
      { enemyId: "wolf_timber", weight: 5 },
      { enemyId: "wolf_dire", weight: 5 },
    ],
  },
  {
    id: "forest_wolves_hard_opposite_2",
    position: { x: -110, y: 0, z: -65 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 15,
    respawnDelaySeconds: 500,
    initialSpawnCount: 7,
    spawnList: [
      { enemyId: "wolf_timber", weight: 5 },
      { enemyId: "wolf_dire", weight: 5 },
    ],
  },
  {
    id: "forest_wolves_hard_opposite_3",
    position: { x: 65, y: 0, z: 110 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 15,
    respawnDelaySeconds: 500,
    initialSpawnCount: 7,
    spawnList: [
      { enemyId: "wolf_timber", weight: 5 },
      { enemyId: "wolf_dire", weight: 5 },
    ],
  },
  {
    id: "mountain_pass_knights_opposite_2",
    position: { x: 35, y: 0, z: 95 },
    radius: 15,
    activationRadius: 100,
    maxEnemies: 2,
    respawnDelaySeconds: 180,
    initialSpawnCount: 2,
    spawnList: [{ enemyId: "rogueknight", weight: 10 }],
  },
  {
    id: "horsie",
    position: { x: 168, y: 0, z: -161 },
    radius: 20,
    activationRadius: 15,
    maxEnemies: 1,
    respawnDelaySeconds: 60,
    initialSpawnCount: 1,
    spawnList: [{ enemyId: "horsie", weight: 10 }],
  },
  {
    id: "stag",
    position: { x: -23, y: 0, z: -6 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 1,
    respawnDelaySeconds: 60,
    initialSpawnCount: 1,
    spawnList: [{ enemyId: "stag", weight: 10 }],
  },
  {
    id: "deer",
    position: { x: -23, y: 0, z: -7 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 1,
    respawnDelaySeconds: 60,
    initialSpawnCount: 1,
    spawnList: [{ enemyId: "deer", weight: 10 }],
  },
  {
    id: "pack",
    position: { x: -56, y: 0, z: -136 },
    radius: 20,
    activationRadius: 100,
    maxEnemies: 9,
    respawnDelaySeconds: 60,
    initialSpawnCount: 9,
    spawnList: [
      { enemyId: "deer", weight: 8 },
      { enemyId: "stag", weight: 2 },
    ],
  },
];
